[package]
name = "auto-updater"
version = "0.1.1"
description = "Firmware auto update utility for EZSP-based Zigbee devices"
license = "MIT"
edition = "2024"
publish = false

[dependencies]
clap.workspace = true
env_logger.workspace = true
ezsp = { workspace = true, features = ["semver"] }
ezsp-fwupd.workspace = true
le-stream.workspace = true
log.workspace = true
semver = { workspace = true, features = ["serde"] }
serde.workspace = true
serde_json.workspace = true
serialport.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }

[[bin]]
name = "ezsp-auto-fwupd"
path = "src/main.rs"

[lints]
workspace = true
