[package]
name = "ezsp-fwupd"
version = "2.0.0"
description = "Firmware update library for EZSP-based Zigbee devices"
license = "MIT"
edition = "2024"
publish = false

[dependencies]
ashv2.workspace = true
async-serialport.workspace = true
bitflags.workspace = true
ezsp.workspace = true
indicatif.workspace = true
le-stream = { workspace = true, features = ["macaddr"] }
log.workspace = true
serialport.workspace = true
tokio = { workspace = true, features = ["rt", "sync"] }
xmodem.workspace = true

[lints]
workspace = true
