[package]
name = "ezsp-fwupd"
version = "1.0.0"
description = "Firmware update library for EZSP-based Zigbee devices"
license = "MIT"
edition = "2024"
publish = false

[dependencies]
ashv2.workspace = true
bitflags.workspace = true
crc.workspace = true
ezsp.workspace = true
indicatif.workspace = true
le-stream = { workspace = true, features = ["macaddr"] }
log.workspace = true
serialport.workspace = true
tokio = { workspace = true, features = ["sync"] }

[lints]
workspace = true
